import React from 'react';
import {
  Box, Typography, Paper, Grid, Card, CardContent, Button, Chip, List, ListItem, ListItemIcon, ListItemText,
} from '@mui/material';
import {
  Assessment, Download, PictureAsPdf, TableChart, TrendingUp,
  Person, CalendarToday, AutoAwesome,
} from '@mui/icons-material';
import PageHeader from '../components/PageHeader';
import { useLang } from '../contexts/LanguageContext';

const reportTemplates = [
  { title: '日健康报告', title_en: 'Daily Health Report', desc: '24小时生命体征汇总与异常事件', desc_en: '24-hour vital signs summary and abnormal events', icon: <CalendarToday />, type: 'daily' },
  { title: '周趋势分析', title_en: 'Weekly Trend Analysis', desc: '7天健康指标变化趋势与AI解读', desc_en: '7-day health metric trends with AI interpretation', icon: <TrendingUp />, type: 'weekly' },
  { title: '月度健康评估', title_en: 'Monthly Health Assessment', desc: '综合健康评分、风险变化与建议', desc_en: 'Overall health score, risk changes, and recommendations', icon: <Assessment />, type: 'monthly' },
  { title: 'AI 智能报告', title_en: 'AI Smart Report', desc: '大模型自动生成个性化健康报告', desc_en: 'Personalized health report auto-generated by an LLM', icon: <AutoAwesome />, type: 'ai', highlight: true },
  { title: '患者档案导出', title_en: 'Patient Profile Export', desc: '完整患者健康数据与设备记录', desc_en: 'Complete patient health data and device records', icon: <Person />, type: 'patient' },
  { title: '临床数据报表', title_en: 'Clinical Data Report', desc: '符合 HL7/FHIR 标准的临床格式', desc_en: 'Clinical format compliant with HL7/FHIR standards', icon: <TableChart />, type: 'clinical' },
];

function ReportCenter() {
  const { t } = useLang();
  return (
    <Box>
      <PageHeader
        title={t('报告中心', 'Report Center')}
        subtitle={t('一键生成健康分析报告，支持 PDF 导出与临床系统对接', 'Generate health analysis reports in one click, with PDF export and clinical system integration')}
        breadcrumbs={[{ label: t('管理控制台', 'Admin Console'), path: '/admin' }, { label: t('报告中心', 'Report Center') }]}
      />

      <Grid container spacing={3}>
        {reportTemplates.map(report => (
          <Grid item xs={12} sm={6} md={4} key={report.type}>
            <Card sx={{
              height: '100%',
              border: report.highlight ? 2 : 0,
              borderColor: 'primary.main',
              background: report.highlight ? 'linear-gradient(135deg, #e3f2fd 0%, #fff 100%)' : 'inherit',
            }}>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
                  <Box sx={{ color: report.highlight ? 'primary.main' : 'text.secondary' }}>{report.icon}</Box>
                  <Typography variant="h6">{t(report.title, report.title_en)}</Typography>
                  {report.highlight && <Chip label="AI" size="small" color="primary" />}
                </Box>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 3, minHeight: 40 }}>
                  {t(report.desc, report.desc_en)}
                </Typography>
                <Box sx={{ display: 'flex', gap: 1 }}>
                  <Button variant="contained" size="small" startIcon={<Assessment />}>{t('生成', 'Generate')}</Button>
                  <Button variant="outlined" size="small" startIcon={<PictureAsPdf />}>PDF</Button>
                  <Button variant="outlined" size="small" startIcon={<Download />}>{t('导出', 'Export')}</Button>
                </Box>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>

      <Paper sx={{ p: 3, mt: 3 }}>
        <Typography variant="h6" gutterBottom>{t('最近生成的报告', 'Recently Generated Reports')}</Typography>
        <List>
          {[
            { name: t('张明 - 6月26日健康日报', 'Zhang Ming - Daily Health Report (Jun 26)'), time: '2024-06-26 08:00', type: 'daily' },
            { name: t('王强 - AI 心血管风险评估报告', 'Wang Qiang - AI Cardiovascular Risk Assessment Report'), time: '2024-06-25 16:30', type: 'ai' },
            { name: t('全体患者 - 6月第三周趋势分析', 'All Patients - Week 3 Trend Analysis (June)'), time: '2024-06-24 09:00', type: 'weekly' },
          ].map((r, i) => (
            <ListItem key={i} secondaryAction={
              <Button size="small" startIcon={<Download />}>{t('下载', 'Download')}</Button>
            }>
              <ListItemIcon><PictureAsPdf color="error" /></ListItemIcon>
              <ListItemText primary={r.name} secondary={r.time} />
              <Chip label={r.type === 'ai' ? t('AI 报告', 'AI Report') : t('标准报告', 'Standard Report')} size="small" color={r.type === 'ai' ? 'primary' : 'default'} sx={{ mr: 2 }} />
            </ListItem>
          ))}
        </List>
      </Paper>
    </Box>
  );
}

export default ReportCenter;
